name: Validate Project Submission

on:
  issues:
    types: [opened, edited, labeled]

jobs:
  validate:
    if: contains(github.event.issue.title, '[Project Submission]')
    runs-on: ubuntu-latest
    steps:
      - name: Check required fields
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const body = context.payload.issue.body;

            // Required fields
            const requiredFields = [
              "Project Name:",
              "Repository URL:",
              "Short Description:",
              "Contribution Level:",
              "Areas of Contribution:"
            ];

            let missing = [];
            for (const field of requiredFields) {
              if (!body.includes(field)) {
                missing.push(field);
              }
            }

            if (missing.length > 0) {
              const message = `⚠️ Thank you for your submission! However, it looks like you are missing the following required fields:\n\n${missing.map(f => `- ${f}`).join("\n")}\n\nPlease edit your issue to include these details.`;
              
              await github.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: message
              });

              // Optionally add a "needs-info" label
              await github.issues.addLabels({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: ["needs-info"]
              });

              core.setFailed("Submission is missing required fields.");
            } else {
              // Add "valid-submission" label
              await github.issues.addLabels({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: ["valid-submission"]
              });
            }
